api:
  paths:
    public-patterns:
      - /images/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /api/v1/auth/**
    public-get:
      - /api/v1/**
    public-put:
      - /api/v1/posts/post-view/**
      - /api/v1/contacts/send-idea
      - /api/v1/contacts/send-contact

common:
  password: htn@123456
  page-size: 10
  page-number: 0
  page-sort: id,desc
  max-auth-token: 10
  verify-code-expire-time: 10